<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.390 Clause 5.1.3.4 V18.0.0 (2024-04) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="ussd-data">
        <xs:annotation>
            <xs:documentation>
                Unstructured Supplementary Services Data
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="language" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="ussd-string" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="error-code" type="xs:int" minOccurs="0" maxOccurs="1"/>
                <xs:element name="anyExt" type="anyExtType" minOccurs="0"/>
                <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:anyAttribute namespace="##any" processContents="lax"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="anyExtType">
        <xs:sequence>
            <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

 <xs:element name="UnstructuredSS-Request" type="emptyType"/>
 <xs:element name="UnstructuredSS-Notify" type="emptyType"/>

    <xs:element name="alertingPattern" type="xs:unsignedByte"/>


    <xs:complexType name="emptyType"/>

</xs:schema>
