<?xml version="1.0" encoding="UTF-8"?>                          <!-- RFC 4354 clause 6.1 -->
<xs:schema targetNamespace="urn:oma:params:xml:ns:poc:poc-settings"
           xmlns="urn:oma:params:xml:ns:poc:poc-settings"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
  
  <!-- MCC160: xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/-->
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../../Common/IMS_XSD/xml.xsd"/>

  <xs:annotation>
    <xs:documentation xml:lang="en">
      XML Schema Definition in support of the Incoming Session
      Barring, Answer Mode, Incoming Personal Alert Barring,
      and Simultaneous Sessions Support in the Push-to-talk
      over Cellular (PoC) service.
    </xs:documentation>
  </xs:annotation>
  
  <xs:element name="poc-settings" type="poc-settingsType"/>
  
  <xs:complexType name="poc-settingsType">
    <xs:sequence>
      <xs:element name="entity" type="entityType"
                  minOccurs="0" maxOccurs="unbounded" />
      <xs:any namespace="##other" processContents="lax"
              minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  
  <xs:complexType name="entityType">
    <xs:sequence>
      <xs:element name="isb-settings" type="isbSettingType"
                  minOccurs="0"/>
      <xs:element name="am-settings" type="amSettingType"
                  minOccurs="0"/>
      <xs:element name="ipab-settings" type="ipabSettingType"
                  minOccurs="0"/>
      <xs:element name="sss-settings" type="sssSettingType"
                  minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax"
              minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  
  <xs:complexType name="isbSettingType">
    <xs:sequence>
      <xs:element name="incoming-session-barring">
        <xs:complexType>
          <xs:attribute name="active" type="xs:boolean"
                        use="required" />
        </xs:complexType>
      </xs:element>
      <xs:any namespace="##any" processContents="lax"
              minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  
  <xs:complexType name="amSettingType">
    <xs:sequence>
      <xs:element name="answer-mode">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="automatic"/>
            <xs:enumeration value="manual"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:any namespace="##any" processContents="lax"
              minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  
  <xs:complexType name="ipabSettingType">
    <xs:sequence>
      <xs:element name="incoming-personal-alert-barring">
        <xs:complexType>
          <xs:attribute name="active" type="xs:boolean"
                        use="required" />
        </xs:complexType>
      </xs:element>
      <xs:any namespace="##any" processContents="lax"
              minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  
  <xs:complexType name="sssSettingType">
    <xs:sequence>
      <xs:element name="simultaneous-sessions-support">
        <xs:complexType>
          <xs:attribute name="active" type="xs:boolean"
                        use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:any namespace="##any" processContents="lax"
              minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  
</xs:schema>
