<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.379 F.4.2 V18.8.0 (2024-09) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="urn:3gpp:ns:affiliationCommand:1.0"
xmlns:mcpttaff="urn:3gpp:ns:affiliationCommand:1.0"
attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:complexType name="affiliate-command" id="affil">
    <xs:sequence>
      <xs:element type="xs:anyURI" name="group" minOccurs="1" maxOccurs="unbounded"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttaff:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  <xs:complexType name="de-affiliate-command">
    <xs:sequence>
      <xs:element type="xs:anyURI" name="group" minOccurs="1" maxOccurs="unbounded"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttaff:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  <xs:element name="command-list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="affiliate" type="mcpttaff:affiliate-command" minOccurs="0" maxOccurs="1"/>
        <xs:element name="de-affiliate" type="mcpttaff:de-affiliate-command" minOccurs="0" maxOccurs="1"/>
        <xs:element name="anyExt" type="mcpttaff:anyExtType" minOccurs="0"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="anyExtType">
    <xs:sequence>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
