<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.379 F.7.2 V18.8.0 (2024-09) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="urn:3gpp:ns:preconfiguredRegroup:1.0"
xmlns:mcpttrgrp="urn:3gpp:ns:preconfiguredRegroup:1.0"
attributeFormDefault="unqualified" elementFormDefault="qualified">

  <!-- root XML element -->
  <xs:element name="mcpttregroup" type="mcpttrgrp:mcpttregroup-Type" id="info"/>

  <xs:complexType name="mcpttregroup-Type">
    <xs:sequence>
      <xs:element name="mcpttregroup-Params" type="mcpttrgrp:mcpttregroup-ParamsType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttrgrp:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType> 

  <xs:complexType name="mcpttregroup-ParamsType">
    <xs:sequence>
      <xs:element name="preconfig-group-id" type="mcpttrgrp:preconfig-group-Type"/>
      <xs:element name="mcptt-regroup-uri" type="mcpttrgrp:mcptt-regroup-uri-Type"/>
      <xs:element name="groups-for-regroup" type="mcpttrgrp:groups-for-regroup-Type" minOccurs="0"/>  
      <xs:element name="users-for-regroup" type="mcpttrgrp:users-for-regroup-Type" minOccurs="0"/>  
      <xs:element name="regroup-action" type="xs:string"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttrgrp:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="preconfig-group-Type">
	<xs:sequence>
	 <xs:element type="xs:anyURI" name="preconfigured-group" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttrgrp:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="mcptt-regroup-uri-Type">
    <xs:sequence>
      <xs:element type="xs:anyURI" name="mcptt-regroup-uri"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttrgrp:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="groups-for-regroup-Type">
    <xs:sequence>
      <xs:element type="xs:anyURI" name="group" maxOccurs="unbounded"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttrgrp:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="users-for-regroup-Type">
    <xs:sequence>
      <xs:element type="xs:anyURI" name="user" maxOccurs="unbounded"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcpttrgrp:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="anyExtType">
    <xs:sequence>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>
