<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.379 Table 9A.3.1.2-1 V18.8.0 (2024-09) -->
<xs:schema
  targetNamespace="urn:3gpp:ns:mcpttPresInfoFA:1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:mcpttPIFA10="urn:3gpp:ns:mcpttPresInfoFA:1.0"
  elementFormDefault="qualified" attributeFormDefault="unqualified">

  <!-- MCPTT functional alias specific child elements of presence element -->
  <xs:element name="p-id-fa" type="xs:string"/>

  <!-- MCPTT functional alias specific child elements of status element -->
  <xs:element name="functionalAlias" type="mcpttPIFA10:functionalAliasType"/>
  <xs:complexType name="functionalAliasType">
    <xs:sequence>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="functionalAliasID" type="xs:anyURI" use="optional"/>
    <xs:attribute name="user" type="xs:anyURI" use="optional"/>
    <xs:attribute name="status" type="mcpttPIFA10:statusType" use="optional"/>
    <xs:attribute name="expires" type="xs:dateTime" use="optional"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>
  <xs:element name="take-over" type="xs:boolean"/>

  <xs:simpleType name="statusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="activating"/>
      <xs:enumeration value="activated"/>
      <xs:enumeration value="deactivating"/>
      <xs:enumeration value="take-over-possible"/>
    </xs:restriction>
  </xs:simpleType>

  </xs:schema>
