<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.484 Clause 10.2.2.3  V18.7.0 (2024-09) -->

<xs:schema xmlns:mcdatauep="urn:3gpp:mcdata:mcdataUEConfig:1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="urn:3gpp:mcdata:mcdataUEConfig:1.0"
  elementFormDefault="qualified" attributeFormDefault="unqualified">

  <!-- MCC160: xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/-->
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../../Common/IMS_XSD/xml.xsd"/>

  <xs:element name="mcdata-UE-configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="mcdata-UE-id" type="mcdatauep:MCDataUEIDType"/>
          <xs:element name="name" type="mcdatauep:NameType"/>
          <xs:element name="anyExt" type="mcdatauep:anyExtType"/>
          <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:element name="common" type="mcdatauep:CommonType"/>
        <xs:element name="on-network" type="mcdatauep:On-networkType"/>
        <xs:element name="anyExt" type="mcdatauep:anyExtType"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="domain" type="xs:anyURI" use="required"/>
      <xs:attribute name="XUI-URI" type="xs:anyURI"/>
      <xs:attribute name="Instance-ID-URN" type="xs:anyURI"/>
      <xs:anyAttribute namespace="##any" processContents="lax"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="NameType">
    <xs:simpleContent>
      <xs:extension base="xs:token">
        <xs:attribute ref="xml:lang"/>
        <xs:attributeGroup ref="mcdatauep:IndexType"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MCDataUEIDType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Instance-ID-URN" type="xs:anyURI"/>
      <xs:element name="IMEI-range" type="mcdatauep:IMEI-rangeType"/>
      <xs:element name="anyExt" type="mcdatauep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attributeGroup ref="mcdatauep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="IMEI-rangeType">
    <xs:sequence>
      <xs:element name="TAC" type="mcdatauep:tacType"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="SNR" type="mcdatauep:snrType"/>
        <xs:element name="SNR-range" type="mcdatauep:SNR-rangeType"/>
      </xs:choice>
      <xs:element name="anyExt" type="mcdatauep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="mcdatauep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="SNR-rangeType">
    <xs:sequence>
      <xs:element name="Low-SNR" type="mcdatauep:snrType"/>
      <xs:element name="High-SNR" type="mcdatauep:snrType"/>
      <xs:element name="anyExt" type="mcdatauep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="mcdatauep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:simpleType name="tac-baseType">
      <xs:restriction base="xs:decimal">
        <xs:totalDigits value="8"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tacType">
    <xs:simpleContent>
      <xs:extension base="mcdatauep:tac-baseType">
        <xs:attributeGroup ref="mcdatauep:IndexType"/>
        <xs:anyAttribute namespace="##any" processContents="lax"/>
    </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="snr-baseType">
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="6"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="snrType">
    <xs:simpleContent>
      <xs:extension base="mcdatauep:snr-baseType">
        <xs:attributeGroup ref="mcdatauep:IndexType"/>
        <xs:anyAttribute namespace="##any" processContents="lax"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="CommonType">
    <xs:sequence>
      <xs:element name="short-data-service">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Max-Simul-SDS-Txns-Nc4" type="xs:positiveInteger"/>
            <xs:element name="SDS-Presentation-Priority">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="MCData-Group-Priority" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="MCData-Group-ID" type="xs:anyURI"/>
                        <xs:element name="group-priority-hierarchy" type="xs:nonNegativeInteger"/> 
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="file-distribution">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Max-Simul-FD-Txns-Nc4" type="xs:positiveInteger"/>
            <xs:element name="FD-Presentation-Priority">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="MCData-Group-Priority" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="MCData-Group-ID" type="xs:anyURI"/>
                        <xs:element name="group-priority-hierarchy" type="xs:nonNegativeInteger"/> 
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="conversation-management">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Conversation-Presentation-Priority">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="MCData-Group-Priority" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="MCData-Group-ID" type="xs:anyURI"/>
                        <xs:element name="group-priority-hierarchy" type="xs:nonNegativeInteger"/> 
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="transmission-control">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Max-Simul-Data-Transmissions-Nc4" type="xs:positiveInteger"/>
            <xs:element name="Max-Data-Transmissions-In-Group-Nc5" type="xs:positiveInteger"/>
            <xs:element name="Data-Presentation-Priority">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="MCData-Group-Priority" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="MCData-Group-ID" type="xs:anyURI"/>
                        <xs:element name="group-priority-hierarchy" type="xs:nonNegativeInteger"/> 
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="reception-control">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Max-Simul-Data-Reception-Nc4" type="xs:positiveInteger"/>
            <xs:element name="Max-Data-Receptions-In-Group-Nc5" type="xs:positiveInteger"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="mcdatauep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="On-networkType">
    <xs:sequence>
      <xs:element name="IPv6Preferred" type="xs:boolean"/>
      <xs:element name="Relay-Service" type="xs:boolean"/>
      <xs:element name="Relayed-MCData-Group" type="mcdatauep:Relayed-MCData-GroupType" minOccurs="0"/>
      <xs:element name="anyExt" type="mcdatauep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence> 
    <xs:attributeGroup ref="mcdatauep:IndexType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="Relayed-MCData-GroupType">
    <xs:sequence>
      <xs:element name="MCData-Group-ID" type="xs:anyURI"/>
      <xs:element name="Relay-Service-Code" type="xs:string"/>
      <xs:element name="anyExt" type="mcdatauep:anyExtType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:attributeGroup name="IndexType">
    <xs:attribute name="index" type="xs:token"/>
  </xs:attributeGroup>

  <xs:complexType name="anyExtType"> 
    <xs:sequence>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
