<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.379 Table 7.4.1.2.2-2 V18.8.0 (2024-09) -->
<xs:schema
  targetNamespace="urn:3gpp:mcsSettings:1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:mcs10Set="urn:3gpp:mcsSettings:1.0"
  elementFormDefault="qualified" attributeFormDefault="unqualified">

  <!-- MCS specific "entity" child elements -->
  <xs:element name="selected-user-profile-index" type="mcs10Set:selected-user-profile-indexType"/>
  <xs:element name="multiplex-support" type="xs:boolean"/>

  <xs:complexType name="selected-user-profile-indexType">
    <xs:sequence>
      <xs:element name="user-profile-index" type="xs:nonNegativeInteger"/>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

</xs:schema>
