<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.282 D.1.2 V18.8.0 (2024-09) -->
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="urn:3gpp:ns:mcdataInfo:1.0"
  xmlns:mcdatainfo="urn:3gpp:ns:mcdataInfo:1.0"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">

  <!-- MCC160: xs:import namespace="http://www.w3.org/2001/04/xmlenc#" schemaLocation="http://www.w3.org/TR/xmlenc-core/xenc-schema.xsd"/-->
  <xs:import namespace="http://www.w3.org/2001/04/xmlenc#" schemaLocation="xenc-schema.xsd"/>

  <!-- root XML element -->
  <xs:element name="mcdatainfo" type="mcdatainfo:mcdatainfo-Type" id="info"/>

  <xs:complexType name="mcdatainfo-Type">
    <xs:sequence>
      <xs:element name="mcdata-Params" type="mcdatainfo:mcdata-ParamsType" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcdatainfo:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="mcdata-ParamsType">
    <xs:sequence>
      <xs:element name="mcdata-access-token" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="request-type" type="xs:string" minOccurs="0"/>
      <xs:element name="mcdata-request-uri" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="mcdata-calling-user-id" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="mcdata-called-party-id" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="mcdata-calling-group-id" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="alert-ind" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="originated-by" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="mcdata-client-id" type="mcdatainfo:contentType" minOccurs="0"/>
      <xs:element name="mcdata-controller-psi" type="mcdatainfo:contentType" minOccurs="0"/>

      <xs:element name="gw-mcdata-usage" type="xs:boolean" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="anyExt" type="mcdatainfo:anyExtType" minOccurs="0"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

<!--    anyExt elements for MCData-Params-->
    <xs:element name="emergency-alert-area-ind" type="xs:boolean"/>
    <xs:element name="group-geo-area-ind" type="xs:boolean"/>
    <xs:element name="pre-established-session-ind" type="xs:boolean"/>
    <xs:element name="call-to-functional-alias-ind" type="xs:boolean"/>

    <xs:element name="mcdata-communication-state" type="mcdatainfo:mcdataCommunicationStateType"/>
    <xs:simpleType name="mcdataCommunicationStateType">
      <xs:restriction base="xs:string">
         <xs:enumeration value="establish-request"/>
         <xs:enumeration value="establish-success"/>
         <xs:enumeration value="establish-fail"/>
         <xs:enumeration value="terminate-request"/>
         <xs:enumeration value="terminated"/>
      </xs:restriction>
    </xs:simpleType>

  <xs:element name="response-type" type="xs:string"/>

    <xs:element name="emergency-ind" type="xs:boolean"/>
    <xs:element name="alert-ind-rcvd" type="xs:boolean"/>
    <xs:element name="mc-org" type="xs:string"/>
    <xs:element name="functional-alias-URI" type="mcdatainfo:contentType"/>
    <xs:element name="user-requested-priority" type="xs:nonNegativeInteger"/>
    <xs:element name="multiple-devices-ind" type="mcdatainfo:contentType"/>
    <xs:element name="imminentperil-ind" type="xs:boolean"/>
    <xs:element name="emergency-ind-rcvd" type="xs:boolean"/>
    <xs:element name="binding-ind" type="xs:boolean"/>
    <xs:element name="binding-fa-uri" type="xs:anyURI"/>
    <xs:element name="unbinding-fa-uri" type="xs:anyURI"/>
    <xs:element name="called-functional-alias-URI" type="mcdatainfo:contentType"/>
    <xs:element name="associated-group-id" type="xs:string"/>

    <xs:element name="store-all-private-comms-in-msgstore" type="xs:boolean"/>
    <xs:element name="store-all-group-comms-in-msgstore" type="xs:boolean"/>
    <xs:element name="store-specific-private-comms-in-msgstore" type="mcdatainfo:storageCtrlType"/>
    <xs:element name="store-specific-group-comms-in-msgstore" type="mcdatainfo:storageCtrlType"/>
    <xs:element name="end-to-end-security" type="xs:boolean"/>
    <xs:element name="comn-participants-criteria" type="xs:string"/>
    <xs:element name="preconfigured-group-id" type="xs:anyURI"/>
    <xs:element name="adhoc-grp-emg-alert-grp-ind" type="xs:boolean"/>
    <xs:element name="adhoc-emergency-ind" type="xs:boolean"/>
    <xs:element name="adhoc-additional-information" type="xs:string"/>
    <xs:element name="adhoc-alert-ind" type="xs:boolean"/>
    <xs:element name="adhoc-alert-ind-rcvd" type="xs:boolean"/>
    <xs:element name="adhoc-alert-participant-list" type="mcdatainfo:mcdataIdListType"/>
    <xs:element name="adhoc-alert-participant-not-ack-list" type="mcdatainfo:mcdataIdListType"/>

    <xs:element name="partner-mcdata-id" type="mcdatainfo:contentType"/>
    <xs:element name="migration-auth-result" type="mcdatainfo:contentType"/>
    <xs:element name="selected-user-profile-index" type="mcdatainfo:selected-user-profile-indexType"/>
    <xs:element name="primary-mcdata-id" type="mcdatainfo:contentType"/>

    <xs:complexType name="mcdataIdListType">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="entry" type="mcdatainfo:EntryType"/>
        <xs:element name="anyExt" type="mcdatainfo:anyExtType" minOccurs="0"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:anyAttribute namespace="##any" processContents="lax"/>
    </xs:complexType>

    <xs:complexType name="EntryType">
      <xs:sequence>
        <xs:element name="uri-entry" type="xs:anyURI"/>
        <xs:element name="display-name" type="xs:string" minOccurs="0"/>
        <xs:element name="anyExt" type="mcdatainfo:anyExtType" minOccurs="0"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:anyAttribute namespace="##any" processContents="lax"/>
    </xs:complexType>

    <xs:simpleType name="storageCtrlType">
      <xs:restriction base="xs:string">
         <xs:enumeration value="enable"/>
         <xs:enumeration value="disable"/>
      </xs:restriction>
    </xs:simpleType>


  <xs:simpleType name="protectionType">
    <xs:restriction base="xs:string">
       <xs:enumeration value="Normal"/>
       <xs:enumeration value="Encrypted"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="contentType">
    <xs:choice>
      <xs:element name="mcdataURI" type="xs:anyURI"/>
      <xs:element name="mcdataString" type="xs:string"/>
      <xs:element name="mcdataBoolean" type="xs:boolean"/>
      <xs:any namespace="##other" processContents="lax"/>
      <xs:element name="anyExt" type="mcdatainfo:anyExtType" minOccurs="0"/>
    </xs:choice>
    <xs:attribute name="type" type="mcdatainfo:protectionType"/>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="selected-user-profile-indexType">
    <xs:sequence>
      <xs:element name="user-profile-index" type="xs:nonNegativeInteger"/>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##any" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="anyExtType">
    <xs:sequence>
      <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="location-of-functional-alias-URI" type="mcdatainfo:contentType"/>

</xs:schema>
