<?xml version="1.0" encoding="utf-8"?>                          <!-- 33.180 D.4.4 V18.1.0 (2024-03) -->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema" xmlns:ds = "http://www.w3.org/2000/09/xmldsig#" 
  xmlns = "urn:3gpp:ns:mcsecKMSKRR:1.0" targetNamespace = "urn:3gpp:ns:mcsecKMSKRR:1.0" elementFormDefault = "qualified" version = "1.0">
  <xsd:import namespace = "http://www.w3.org/2000/09/xmldsig#"/>

    <!-- An identifier for this type of response -->
  <xsd:element type = "KmsRedirectResponseType" name = "KmsRedirectResponse"/>

  <xsd:complexType name = "KmsRedirectResponseType">
    <xsd:sequence>
      <!-- The date and time -->
      <xsd:element type = "xsd:dateTime" name = "Time" minOccurs = "1" maxOccurs = "1"/>
      <!-- The identity of the KRR creator. -->
      <xsd:element type = "xsd:anyURI" name = "KRRCreatorUri" minOccurs = "1" maxOccurs = "1"/>
      <!-- The MIKEY initiating identity used within the MIKEY message (IDRi). -->
      <xsd:element type = "xsd:anyURI" name = "InitiatorUri" minOccurs = "1" maxOccurs = "1"/>
      <!-- The MIKEY initiating KMS URI used within the MIKEY message (IDRkmsi). -->
      <xsd:element type = "xsd:anyURI" name = "InitiatorKmsUri" minOccurs = "1" maxOccurs = "1"/>
      <!-- The MIKEY receiving identity used within the MIKEY message (IDRr). -->
      <xsd:element type = "xsd:anyURI" name = "ReceiverUri" minOccurs = "1" maxOccurs = "1"/>
      <!-- The MIKEY receiving KMS URI used within the MIKEY message (IDRkmsr). --> 
      <xsd:element type = "xsd:anyURI" name = "ReceiverKmsUri" minOccurs = "1" maxOccurs = "1"/>
      <!-- The initiator list containing a list of acceptable KMS URIs (List of IDRkmsi's). -->
	  <xsd:element name = "InitiatorKmsList" type = "KmsUriListType" minOccurs = "1" maxOccurs = "1"/>
      <!-- The receiver list containing a list of acceptable KMS URIs (List of IDRkmsr's). -->
      <xsd:element name = "ReceiverKmsList" type = "KmsUriListType" minOccurs = "1" maxOccurs = "1"/>
      <!-- An embedded received KRR (optional, used if KRR is generated from a received KRR). -->
      <xsd:element name = "ReceivedKmsRedirectResponse" type = "ReceivedKmsRedirectResponseType" minOccurs = "0" maxOccurs = "1"/>
      <!-- Allow extensions -->
      <xsd:any namespace = "##other" processContents = "lax" minOccurs = "0" maxOccurs = "unbounded"/>
      <!-- A signature (using the originating identity) over the entire message (optional, but recommended). -->
      <xsd:element name="Signature" type = "ds:SignatureType" minOccurs = "0"/>
    </xsd:sequence>
    <xsd:attribute name = "Id" type = "xsd:string"/>
    <xsd:attribute name = "Version" type = "xsd:string" fixed="1.0.0"/>
    <xsd:anyAttribute namespace = "##other" processContents = "lax"/>
  </xsd:complexType>

  <xsd:complexType name = "KmsUriListType">
    <xsd:sequence>
      <xsd:choice maxOccurs = "1">
        <xsd:sequence>
          <xsd:element type="xsd:string" name="ANY" fixed=""/>
        </xsd:sequence>
        <xsd:sequence>
          <xsd:element type = "xsd:anyURI" name = "KmsUri" minOccurs = "0" maxOccurs = "unbounded"/>
        </xsd:sequence>
      </xsd:choice>
      <xsd:any namespace = "##other" processContents = "lax" minOccurs = "0" maxOccurs = "unbounded"/>
    </xsd:sequence>
    <xsd:anyAttribute namespace = "##other" processContents = "lax"/>
  </xsd:complexType>

  <xsd:complexType name = "ReceivedKmsRedirectResponseType">
    <xsd:sequence>
      <xsd:element name = "KmsRedirectResponse" type = "KmsRedirectResponseType" minOccurs = "1" maxOccurs = "1"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
