<?xml version="1.0" encoding="UTF-8"?>                          <!-- 24.109 Annex C.1 V18.0.0 (2023-12) -->
<xs:schema targetNamespace="uri:3gpp-gba"
    xmlns:gba="uri:3gpp-gba"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

  <xs:complexType name="tExtension">
    <xs:sequence>
      <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- definition of the root element containing B-TID and key lifetime -->
  <xs:complexType name="bootstrappingInfoType">
    <xs:sequence>
       <xs:element name="btid" type="xs:string"/>
       <xs:element name="lifetime" type="xs:dateTime"/>
       <xs:element name="Extension" type="gba:tExtension" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- the root element -->
  <xs:element name="BootstrappingInfo" type="gba:bootstrappingInfoType"/>

  <!-- extension elements included in the Extension element of the root BootstrappingInfo element -->
  <xs:element name="currenttime" type="xs:dateTime"/>


</xs:schema>
